<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
<<<<<<< HEAD
=======
    'Laracasts\\Flash' => array($vendorDir . '/laracasts/flash/src'),
>>>>>>> 8545c672bd290d38922760fe75108e83faedae85
    'Detection' => array($vendorDir . '/mobiledetect/mobiledetectlib/namespaced'),
);
